spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memory
    username: alexander
    password: # Add your password here
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true